/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppConfig: typeof import('./src/components/AppConfig.vue')['default']
    AppTopbar: typeof import('./src/components/AppTopbar.vue')['default']
    Button: typeof import('primevue/button')['default']
    Carousel: typeof import('primevue/carousel')['default']
    copy: typeof import('./src/components/home/HighlightsWidget copy.vue')['default']
    FeaturesWidget: typeof import('./src/components/home/FeaturesWidget.vue')['default']
    FooterWidget: typeof import('./src/components/home/FooterWidget.vue')['default']
    FooterWidgetOrig: typeof import('./src/components/home/FooterWidgetOrig.vue')['default']
    HeroWidget: typeof import('./src/components/home/HeroWidget.vue')['default']
    HighlightsWidget: typeof import('./src/components/home/HighlightsWidget.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    ProductOverviewWidget: typeof import('./src/components/dashboard/ProductOverviewWidget.vue')['default']
    RecentActivityWidget: typeof import('./src/components/dashboard/RecentActivityWidget.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SalesTrendWidget: typeof import('./src/components/dashboard/SalesTrendWidget.vue')['default']
    StatsWidget: typeof import('./src/components/dashboard/StatsWidget.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    TopbarWidget: typeof import('./src/components/home/TopbarWidget.vue')['default']
    UserLogin: typeof import('./src/components/UserLogin.vue')['default']
  }
}
