/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppConfig: typeof import('./src/components/AppConfig.vue')['default']
    AuthTest: typeof import('./src/components/AuthTest.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('./src/components/list/Card.vue')['default']
    CardFeature: typeof import('./src/components/list/CardFeature.vue')['default']
    FeaturesWidget: typeof import('./src/components/home/FeaturesWidget.vue')['default']
    Fieldset: typeof import('primevue/fieldset')['default']
    FileUploader: typeof import('./src/components/FileUploader.vue')['default']
    FooterWidget: typeof import('./src/components/home/FooterWidget.vue')['default']
    Galleria: typeof import('primevue/galleria')['default']
    HeroWidget: typeof import('./src/components/home/HeroWidget.vue')['default']
    HighlightExtraWidget: typeof import('./src/components/home/HighlightExtraWidget.vue')['default']
    HighlightsWidget: typeof import('./src/components/home/HighlightsWidget.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    ListForm: typeof import('./src/components/list/ListForm.vue')['default']
    ListFormComponent: typeof import('./src/components/list/ListFormComponent.vue')['default']
    ListListing: typeof import('./src/components/list/ListListing.vue')['default']
    Message: typeof import('primevue/message')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SlideFeature: typeof import('./src/components/home/SlideFeature.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    Textarea: typeof import('primevue/textarea')['default']
    TopbarWidget: typeof import('./src/components/home/TopbarWidget.vue')['default']
    UserLogin: typeof import('./src/components/UserLogin.vue')['default']
    UserRegister: typeof import('./src/components/UserRegister.vue')['default']
  }
}
